services:
  - type: web
    name: gezx-downloader-bot
    env: docker
    plan: free
    autoDeploy: true
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: TELEGRAM_API_ID
        sync: false
      - key: TELEGRAM_API_HASH
        sync: false
      - key: ADMIN_IDS
        sync: false
      - key: FORCE_JOIN_CHANNEL
        sync: false
      - key: PORT
        value: 8080
